[project]
org-name = "ballerina"
version = "0.9.2"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-jira"
keywords = ["ballerina", "jira","jira7"]
license = ["Apache-2.0"]
