[project]
org-name = "ballerinax"
version = "0.9.3"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-jira"
keywords = ["ballerina", "jira","jira"]
license = ["Apache-2.0"]
