name: Deployment

on: [release]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      build -a -c --skip-tests
              env:
                  JIRA_URL: ${{ secrets.JIRA_URL }}
                  JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
                  JIRA_PASS: ${{ secrets.JIRA_PASS }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      push -a
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
                  
